name: Update Language Statistics

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

permissions:
  contents: write

jobs:
  update-stats:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout profile repository
        uses: actions/checkout@v4

      - name: Generate language statistics
        uses: StefVuck/Github-Language-Stats@v1.2.0
        with:
          github_token: ${{ secrets.STATS_TOKEN }}
          visualization_types: "leaderboard"
          output_path: "stats"
          include_forks: "false"
          exclude_languages: "HTML,CSS"
          top_repos_count: "5"
          dark_mode: "false"
          use_loc: "false"
